<?php
/**
  * Implements hook_menu()
  */
function mha_ereg_menu(){
	$items['ereg'] = array(
    'title' => 'eRegistration', 
    'page callback' => 'mha_ereg_config',  
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
	
	$items['ereg/event/%'] = array(
    'title' => 'eRegistration', 
    'page callback' => 'mha_ereg_event',
		'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
	
	return $items;
}

function mha_ereg_config(){
	global $user;
	if($user->uid){
		$output = '<p>Select an event</p>';
		$output .= views_embed_view('eregistration_events');
	}
	else{
		$output = theme('image', array(
			'path' => drupal_get_path('module', 'mha_ereg') .'/images/mha-new-trans.png',
		));
		$output .= '<p>Eletronic Event Registration</p>';
		$output .= render(drupal_get_form('user_login'));
	}
	return $output;
}

function mha_ereg_form_alter(&$form, &$form_state, $form_id){
	if($form_id == 'user_login'){
		$form['form_js']['#after_build'] = array('_mha_ereg_add_js');
	}
}

function mha_ereg_user_login(&$edit, $account) {
	if(arg(0) == 'ereg'){
		$edit['redirect'] = 'ereg';
	}
}


function _mha_ereg_add_js($element){
	drupal_add_js(drupal_get_path('module', 'mha_ereg') . '/js/mha_ereg.js');
	return $element;
}

function mha_ereg_event($nid = null){
	if($nid == null){
		return 'No event specified.';
	}
	else{
		$event = node_load($nid);
		if($event->type != 'event'){
			return 'No valid event specified.';
		}
		$output = '<h1>' . $event->title . ' eRegistration</h1>';
		$output .= render(drupal_get_form('mha_ereg_registration_form', $event));
		return $output;
	}
}

function mha_ereg_registration_form($form, &$form_state, $event){
	$form['event'] = array(
		'#type' => 'value',
		'#value' => $event->nid,
	);
	
	$form['non_member'] = array(
		'#type' => 'fieldset',
		'#collapsible' => true,
		'#title' => t('Non-Member'),
		'#collapsed' => true,
	);
	
	$form['non_member']['non_member_name'] = array(
		'#type' => 'textfield',
		'#title' => t('Full Name'),
	);
	
	return $form;
}