<?php
/**
  * Implements hook_menu()
  */
function mha_dd_menu(){
	$items['membership/dd'] = array(
    'title' => 'Test the Direct Debit', 
    'page callback' => 'mha_dd_page',
    'access arguments' => array('administer membership'),
    'type' => MENU_NORMAL_ITEM,
  );
	
	$items['membership/dd/webhook'] = array(
    'title' => 'Direct Debit Webhook', 
    'page callback' => 'mha_dd_webhook',  
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
	
	return $items;
}

function mha_dd_page(){
	$output = '<div id="direct-debit-container">';
	$output .= '<h2>Pay by Direct Debit</h2>';
	$output .= '<p>Members who opt to pay their subscription fees via Direct Debit will benefit from futher discounts on their membership fees wih Full/Alumni & Affiliate Members pay &pound;5.00 a year and Student Members pay &pound;2.50 a year.';
	$output .= '<p>All direct debit payments are processed securely by GoCardless.com, this will be what shows up on your bank statement you will be redirected to GoCardless to complete the initialiseationn of you Direct Debit.</p>';
	$output .= render(drupal_get_form('mha_dd_page_form'));
	$output .= '</div>';
	return $output;
}
function mha_dd_page_form(){
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Pay by Direct Debit'),
	);
	$form['submit']['#attributes']['class'][] = 'btn-success';
	return $form;
}
function mha_dd_page_form_submit($form, &$form_state){
	include_once 'lib/GoCardless.php';
	$account = $_SESSION['account'];
	
	
	switch($account->field_membership_class[LANGUAGE_NONE][0]['value']){
		case 'full' :
			$amount = 5.00;
			$item = 'Full/Alumni Membership';
			$period = '3 years from date of approval';
			break;
		case 'affiliate' :
			$amount = 5.00;
			$item = 'Affiliate Membership';
			$period = '3 years from date of approval (Affiliate members must also be ratified at an AGM)';
			break;
		case 'student' :
			$amount = 2.5;
			$item = 'Student Membership';
			$period = 'Until the end of your current course';
			break;
	}
	//GoCardless::$environment = 'production';
	
	// Set config vars
	$account_details = array(
		'app_id'        => 'RC2MZXWC4XZXS02X4HWY3NDSGQTRA4WKA4AMNFGKDDYC59XDZ902BAAWQY16FGEP',
		'app_secret'    => 'JG1QC4RM62RVG73H6TPY0K66EH86C61RZKFZ5SMXVS93X4REHC169435T0KPE6PC',
		'merchant_id'   => '0XRGDXS5E5',
		'access_token'  => '4WQZTV1Y51YTCZSHN4AT8SNVVEDR8NN7N3C6R7Y1JT120FBG610BR1N86QBPPNNR',
		'state' => 'test state'
	);
	
	// Initialize GoCardless
	GoCardless::set_account_details($account_details);
	
	$subscription_details = array(
		'amount'           => $amount,
		'interval_length'  => 12,
		'interval_unit'    => 'month',
		'name' => $item,
		'description' => 'Direct Debit Payment for member MHA-905',
		'state' => '905',
		'resource_uri' => 'http://slide.manorhallassociation.co.uk/membership/dd/webhook'
		
	);

	// Generate the url
	$subscription_url = GoCardless::new_subscription_url($subscription_details);
	
	drupal_goto($subscription_url);

}
function mha_dd_webhook(){
	$webhook = file_get_contents('php://input');
	$webhook_array = json_decode($webhook, true);
	watchdog('Direct Debit', print_r($webhook_array, true));
	$bill = GoCardless::find('PM0000HM6MZ26A');
	$webhook_valid = GoCardless::validate_webhook($webhook_array['payload']);
	header('HTTP/1.1 200 OK');
	if($webhook_array['payload']['action'] == 'paid'){
		
		$query = new EntityFieldQuery();
		$query->entityCondition('entity_type', 'user')
			->fieldCondition('field_direct_debit_subscription', 'value', $webhook_array['payload']['bills'][0]['source_id'], '=');

		$results = $query->execute();
		$users_ids = array_keys($results['user']);

		$users = user_load_multiple(array_keys($results['user']));
		foreach($users as $account) {
			$account->field_user_status[LANGUAGE_NONE][0]['value'] = 'paid';
			$account->field_expiry_[LANGUAGE_NONE][0]['value'] = strtotime('+1 years');
			user_save($account);
			mha_permission_log_entry(t('Direct Debit Payment: !name', array('!name' => $account->realname)), $account->uid);
		}
	}
}

function mha_dd_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id = 'mha_dd_page_form') {
    $form['actions']['submit']['#attributes']['class'][] = 'btn-success';
  }
}
