<?php
/**
 * Implements hook_menu().
 */
function eu_cookie_compliance_menu() {
  $items['admin/config/eu-cookie-compliance'] = array(
    'title' => 'EU Cookie Compliance',
    'description' => 'Make your website compliant with the EU Directive on Privacy and Electronic Communications.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('eu_cookie_compliance_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'eu_cookie_compliance.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function eu_cookie_compliance_init() {
  $enabled = eu_cookie_compliance_get_settings('popup_enabled');
  if ($enabled) {
    $path = drupal_get_path('module', 'eu_cookie_compliance');
    drupal_add_css($path . '/css/eu_cookie_compliance.css');
    drupal_add_js($path . '/js/eu_cookie_compliance.js', array('scope'=>'footer'));

    $popup_settings = eu_cookie_compliance_get_settings();
    if ($popup_settings['popup_enabled']) {
      global $language;
      $popup_text_info = str_replace(array("\r", "\n"), '', $popup_settings['popup_info']['value']);
      $html_info = theme('eu_cookie_compliance_popup_info', array('message'=>$popup_text_info));
    
      $variables = array(
        'popup_enabled' => $popup_settings['popup_enabled'],
        'popup_html_info' => $html_info,
        'popup_height' => ($popup_settings['popup_height']) ? (int) $popup_settings['popup_height'] : 'auto',
        'popup_width' => (drupal_substr($popup_settings['popup_width'], -1) == '%') ? $popup_settings['popup_width'] : (int) $popup_settings['popup_width'],
        'popup_delay' => (int) ($popup_settings['popup_delay'] * 1000),
        'popup_link' => $popup_settings['popup_link'],
        'popup_position' => $popup_settings['popup_position'],
        'popup_language' => $language->language,
      );
      drupal_add_js(array('eu_cookie_compliance' => $variables), "setting", 'footer');
    }
  }
}

/**
 * Implements hook_theme().
 */
function eu_cookie_compliance_theme() {
  $path = drupal_get_path('module', 'eu_cookie_compliance') . '/theme';
  return array(
    'eu_cookie_compliance_popup_info' => array(
      'template' => 'eu-cookie-compliance-popup-info',
      'arguments' => array('message' => NULL),
      'path' => $path,
    ),
  );
}


/**
 *
 * Retrieves settings from the database for a current language.
 * 
 * @global type $language
 * @param type $setting
 * @return type 
 */
function eu_cookie_compliance_get_settings($setting = 'all') {
  global $language;
  $popup_settings = variable_get('eu_cookie_compliance_' . $language->language, array());
  if ($setting == 'all') return $popup_settings;

  if (isset($popup_settings[$setting])){
    return $popup_settings[$setting];
  }
  return '';
}